integer_server:
  address: "http://192.168.102.91:8090/soap/IOrionPro"     
  title_service: "Orion Pro Integration Service"
server:
  port: 8082
  integrserv: "http://192.168.102.91:8090"
session:
  ttl: 24h
  secret: "7g{Q0z7>)9l@"
db:
  driver: "sqlite3"
  source: "internal/storage/main/sqlite/db/SKUD.db"
  